!!python/object:napari_workflows._workflow.Workflow
_tasks:
  membrane-gb: !!python/tuple
  - &id001 !!python/name:skimage._shared.filters.gaussian ''
  - membrane
  - 1
  - null
  - nearest
  - 0
  - false
  - 4.0
  membrane-label: !!python/tuple
  - &id002 !!python/name:skimage.measure._label.label ''
  - membrane-threshold
  - null
  - false
  membrane-threshold: !!python/tuple
  - &id003 !!python/name:napari_segment_blobs_and_things_with_membranes.threshold_otsu ''
  - membrane-gb
  nucleus-gb: !!python/tuple
  - *id001
  - nucleus
  - 1
  - null
  - nearest
  - 0
  - false
  - 4.0
  nucleus-label: !!python/tuple
  - *id002
  - nucleus-threshold
  - null
  - false
  nucleus-threshold: !!python/tuple
  - *id003
  - nucleus-gb
