CANVAS_SCALE: 1.0
CANVAS_SIZE:
- 1024
- 1024
CLEAR_LAYERS_ON_NEW_SCENE: false
OVERRIDE_CANVAS_SIZE: false
PREFERRED_READER: bioio-ome-tiff
SCENE_HANDLING: Open Scene Widget
UNPACK_CHANNELS_AS_LAYERS: true
