name: docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e .[docs]

      - name: Deploy docs to GitHub Pages
        if: github.event_name == 'push'
        run: mkdocs gh-deploy --strict --force

      - name: Test that docs build without error
        if: github.event_name == 'pull_request'
        run: mkdocs build --strict
