# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Test

on:
  push:
    branches: [main]
    tags: ["v*"] # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/reusable_run_tox_test.yml
    with:
      coverage: true
